var bookmark= [
{
    slug: 'world-lost',
    name: 'Google Inc',
    author: 'google inc',
    ititle: 'g',
    website: 'm.google.com',
    github: 'github.com/bhuvanameenakshi/World_Lost',
    koran:'drive.google.com - mail.google.com - YouTube.com cloud.google.com - play.google.com - video.google.com - podcast.google.com - music.google.com',
  },
  {
    slug: 'kulit',
    name: 'Jerawat apa jerawat',
    author: 'manonline',
    ititle: 'G',
    website: 's.mp4',
    github: 'github.com/kulit/',
    koran: 'Jerawat biasanya rentan terjadi pada kulit berminyak, tapi jerawat bisa juga terjadi pada kulit kering dan kulit Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek sensit…entures<h3>NAME</h3> kulit kering dan kulit Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek sensit…entureskulit kering dan kulit Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek Melasma dan flek hitam adalah jenis hiperpigmentasi, namun beda penyebab dan cara mengatasinya. Cek apa perbedaan flek sensit…entures',
  },
  {
    slug: 'vernissage',
    name: 'Vernissage',
    author: 'Platane',
    ititle: 'platane_',
    website: 'b.mp4',
    github: 'github.com/Platane/js13k-2017',
  koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or adventuresthe best gift you could have given her was a lifetime or adventuresthe best gift you could have given her was a lifetime or adventuresthe best gift you could have given her was a lifetime or adventuresthe best gift you could have given her was a lifetime or adventuresthe best gift you could have given her was a lifetime or adventuresthe best gift you could haime or adventuresthe best gift you could have given her was a lifetime or adventures',
  },
  {
    slug: 'coconutty',
    name: 'Coconutty',
    author: 'Mary Knize',
    ititle: 'captainpainway',
    website: 'a.mp4',
    github: 'github.com/captainpainway/coconutty',
  koran: 'sgggg gggg yuuuhhggg',
  },
  {
    slug: 'lost-pacman',
    name: 'Lost Pacman',
    author: 'MarcGuinea',
    ititle: 'MarcGuineaCasas',
    website: 'marcguinea.com',
    github: 'github.com/mguinea/lost-pacman',
  koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'polyhedron-runner',
    name: 'Polyhedron Runner',
    author: 'Alex Swan',
    ititle: 'BoldBigflank',
    website: 'bold-it.com',
    github: 'github.com/BoldBigflank/js13k-polyhedron',
    koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'she-is-my-universe',
    name: 'She is my universe',
    author: 'Madmarcel',
    ititle: 'madmarcel',
    website: '',
    github: 'github.com/madmarcel/js13k2017', koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'spacewrecked',
    name: 'Spacewrecked',
    author: 'Sorskoot',
    ititle: 'Sorskoot',
    website: 'timmykokke.com',
    github: 'github.com/sorskoot/js13kgames_2017_Lost', koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'shifted-dimensions',
    name: 'Shifted Dimensions',
    author: 'Nylki',
    ititle: 'nylk',
    website: 'github.com/nylki',
    github: 'github.com/nylki/shifted-dimensions', koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'wandering-moon',
    name: 'Wandering Moon',
    author: 'Jack Greenberg',
    ititle: 'thprgrmmrjck',
    website: '',
    github: 'github.com/theProgrammerJack/js13k2017', koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'lost-in-guam',
    name: 'Lost in Guam',
    author: 'Kenneth Banico',
    ititle: 'kjdesigns671',
    website: '',
    github: 'github.com/kbanico/lost-in-guam-vr-game', koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'balloon-problems',
    name: 'Balloon Problems',
    author: 'Fasility',
    ititle: 'Fasility_VR',
    website: 'fasility.com',
    github: 'github.com/flowerio/balloon-problems', koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'lost-in-my-mind',
    name: 'Lost in my mind',
    author: 'Lasagne Games',
    ititle: 'Lazyeels',
    website: '',
    github: 'github.com/lazyeels/js13kb', koran: 'the best gift you could have given her was a lifetime or adventures the best gift you could have given her was a lifetime or ',
  },
  {
    slug: 'lost-in-the-forest-dungeon',
    name: 'Lost In The Forest Dungeon',
    author: 'Luke',
    ititle: 'cannl',
    website: 'lc-apps.co.uk',
    github: 'github.com/lcapps-luke/js13k-lost',
  },
  {
    slug: 'galacticdiamond',
    name: 'GalacticDiamond',
    author: 'Mitruska',
    ititle: 'mitruska_',
    website: '',
    github: 'github.com/mitruch/GalacticDiamond-JS13KGames-2017',
  },
  {
    slug: 'cat-meow',
    name: 'Cat Meow',
    author: 'Lislis',
    ititle: '',
    website: '',
    github: 'github.com/lislis/cat-meow',
  },
  {
    slug: 'metamorphosis',
    name: 'Metamorphosis',
    author: 'Steff and Tanyuan',
    ititle: '',
    website: '',
    github: 'github.com/tanyuan/metamorphosis',
  },
  {
    slug: 'a-snake',
    name: 'A-Snake',
    author: 'Nick Frazier',
    ititle: 'nrf',
    website: 'nickfrazier.com',
    github: 'github.com/fraziern/vrsnake',
  },
  {
    slug: 'wherewhat',
    name: 'Where? What?',
    author: '..Katu..',
    ititle: '',
    website: '',
    github: 'github.com/katubrd/LostVR',
  },
  {
    slug: 'dont-let-your-dreams-be-memes',
    name: 'Don\'t let your dreams be memes',
    author: 'Mark Vasilkov',
    ititle: 'mvasilkov',
    website: 'mvasilkov.ovh',
    github: 'github.com/mvasilkov/aframe13k',
  },
  {
    slug: 'fly-south',
    name: 'Fly South',
    author: 'Christian Paul (jaller94)',
    ititle: '',
    website: 'chrpaul.de',
    github: 'github.com/jaller94/fly-south',
  },
  {
    slug: 'prisonri0t',
    name: 'PrisonRi0t',
    author: 'Sondor',
    ititle: '',
    website: '',
    github: 'github.com/gabboraron/prison',
  },
  {
    slug: 'debriss',
    name: 'DebrISS',
    author: 'Kovolmany',
    ititle: '',
    website: '',
    github: 'github.com/gabboraron/iss',
  },
  {
    slug: 'vr-racing',
    name: 'VR Racing',
    author: 'Vedansh Bhartia and Kartikey Pandey',
    ititle: '',
    website: '',
    github: 'github.com/vedanshbhartia/vr_racing',
  },
  {
    slug: 'a-box-invaders',
    name: 'A-box Invaders',
    author: 'Felipe Do E. Santo',
    ititle: 'felipez3r0',
    website: 'hardcodigo.com.br',
    github: 'github.com/felipez3r0/a-box-invaders',
  },
  {
    slug: 'world-lost',
    name: 'World Lost',
    author: 'Ms. K. Bhuvana Meenakshi',
    ititle: 'bhuvanakotees1',
    website: 'bhuvanameenakshik.wixsite.com/bhuvanameenakshi',
    github: 'github.com/bhuvanameenakshi/World_Lost',
  },
  {
    slug: 'give-space',
    name: 'Give Space',
    author: 'Ram',
    ititle: 'ram_gurumukhi',
    website: 'gurumukhi.wordpress.com',
    github: 'github.com/gurumukhi/13kGiveSpaceGame',
  },
  {
    slug: 'lost-in-metaverse',
    name: 'Lost in Metaverse',
    author: 'Karan Ganesan',
    ititle: 'karanganesan',
    website: 'linkedin.com/in/karanganesan',
    github: 'github.com/karanganesan/Lost_in_Metaverse',
  },
  {
    slug: 'emma-3d',
    name: 'Emma-3D',
    author: 'Prateek Roushan',
    ititle: '',
    website: '',
    github: 'github.com/coderprateek/Emma-3D',
  },
];
